config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "neighborhoods#index"
  resources :neighborhoods, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
  belongs_to :neighborhood
end

app/models/bar.rb
class Bar < ApplicationRecord
  belongs_to :neighborhood
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  has_many :bars
  has_many :arts

  def get_coords_from_location
    url = "https://maps.googleapis.com/maps/api/geocode/json?address=#{urlify(name)},San+Francisco,CA&key=AIzaSyBi_LAVQdQK86p7BcCxTxYuPr1lKVC5HAw"
    response = HTTParty.get(url, verify: false)["results"]
    return response.first["geometry"]["location"]

  end

  def urlify(location)
    location.gsub(" ", "+")
  end
end

app/models/yelp_api.rb
class YelpAPI


  require 'yelp'


  def initialize
    @client = Yelp::Client.new({
             consumer_key: Rails.application.secrets.yelp_consumer_key,
            consumer_secret: Rails.application.secrets.yelp_consumer_secret,
            token: Rails.application.secrets.yelp_token,
            token_secret: Rails.application.secrets.yelp_token_secret
      })
    @params = {term: "bars", sort: 0, limit: 10, radius_filter: 1000, category_filter: "nightlife"}
  end

  def get_top_bars(neighborhood)
    coords = neighborhood.get_coords_from_location
    search_coords = {}
    search_coords[:longitude] = coords["lng"]
    search_coords[:latitude] = coords["lat"]
    top_ten = @client.search_by_coordinates(search_coords, @params)
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  @neighborhoods = Neighborhood.all

end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  def index
    @neighborhoods = Neighborhood.all
  end

  def show
    @neighborhoods = Neighborhood.all
    @neighborhood = Neighborhood.find(params[:id])
    @bars = YelpAPI.new.get_top_bars(@neighborhood).businesses
  end

  private

  def neighborhood_params
    params.require(:neighborhood).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtBarCrawl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://code.jquery.com/jquery-1.10.1.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyASEqKudGyICaxwHhXNI26baXLKx9QRd-k&callback=initMap"
    async defer></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Josefin+Slab" rel="stylesheet">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body id="page-top" class="index">


    <%= yield %>


    <!-- Footer -->
    <footer class="text-center">

        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        By Hannah, Ruby, Corinne, Brittany, Solene
                    </div>
                </div>
            </div>
        </div>
    </footer>
  </body>
</html>

app/views/neighborhoods/_art.html.erb
<section class="success" id="about">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 text-center">
                <h2 class="special-font">Art in the Neighborhood</h2>
                <hr class="star-light">
            </div>

            <% neighborhood.arts.each do |art| %>
                <div class="col-xs-12 col-sm-6 portfolio-item">
                    <div class="row">
                        <a href="<%= art.link %>"><h3><%= art.name %> </h3></a>
                        <h6>by <%= art.artist %></h6>

                        <div class="col-xs-6">
                            <% if art.image_url %>
                                <%= image_tag art.image_url, class: "img-rounded img-responsive" %>
                            <% end %>

                        </div>

                        <div class="col-xs-6">
                            <p class="art-description"><%= art.description %></p>
                        </div>
                    </div>


                 </div>

            <% end %>
        </div>
    </div>
</section>

app/views/neighborhoods/_bars.html.erb
<section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="special-font">Bars</h2>
                <hr class="star-primary">
            </div>
        </div>

  <div class="row">
      <% bars.each do |bar| %>
        <div class="col-xs-12 col-sm-6 portfolio-item">
          <div class="row">
            <div class="col-xs-3">
              <%= link_to bar.url, :target => "_blank" do %>
                <%= image_tag bar.image_url, class: "img-rounded img-responsive" %>
              <% end %>
            </div>
            <div class="col-xs-9" id="bar-info">
              <%= link_to bar.name, bar.url, :target => "_blank" %><br>
              Yelp Rating: <%= image_tag bar.rating_img_url %><br>
              <% bar.categories.each_with_index do |category, index| %>
                <%= category[0] %><%= "," unless index == bar.categories.length - 1 %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>



    </div>
</section>

app/views/neighborhoods/index.html.erb
<body id="page-top" class="index">


    <!-- Header -->
    <header id="front-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">

                    <img class="img-responsive" src="http://ka-advance.com/wp-content/uploads/2015/02/KA-Advance-Art_San_Francisco_Header.png" alt="">
                    <div class="intro-text">
                        <span class="name special-font">F.O.M.A.A.</span>
                        <hr class="star-light">
                        <span class="skills">Your SF Guide to Not Missing Out on Art or Alcohol</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

<footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                <h1>Choose Your Neighborhood to Explore!</h1>

            <!-- Brand and toggle get grouped for better mobile display -->

            </div>
            <!-- /.navbar-collapse -->
        <!-- /.container-fluid -->

                    <div class="footer-col col-xs-12 text-center">

                <ul class="nav navbar-nav navbar-right neighb-list text-center">

                <% @neighborhoods.each do |neighb| %>
                  <li><%= link_to neighb.name, neighborhood_path(neighb.id) %></li>
                <% end %>

                  </ul>
                    </div>


                </div>
            </div>
        </div>

    </footer>



    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/freelancer.min.js"></script>

</body>

</html>

app/views/neighborhoods/show.html.erb
<body id="page-top" class="index">

    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
           <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <%= link_to "F.O.M.A.A.", neighborhoods_path, class: "navbar-brand special-font" %>
            </div>


            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <!-- <a class="navbar-brand" href="#page-top">SF Art Bar Crawl</a> -->
            </div>
                <ul class="nav navbar-nav navbar-right">

                    <% @neighborhoods.each do |neighb| %>
                        <li><%= link_to neighb.name, neighborhood_path(neighb.id) %></li>
                    <% end %>

                  </ul>
            </div>
             </div>
        </nav>


    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-text">

                        <span class="name special-font" style="font-family: 'Amatic SC', cursive;"><%= @neighborhood.name %></span>
                        <hr class="star-light">
                        <span class="skills">San Francisco, California</span>
                        <div style="height: 20px;"></div>
                        <img class="img-responsive" src="<%= @neighborhood.image_url %>" alt="">
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="wrapper">
        <div id="<%= @neighborhood.name.downcase.gsub(" ", "-" ) %>" class="map"></div>
    </div>

    <%= render "bars", bars: @bars %>
    <%= render "art", neighborhood: @neighborhood %>


    <!-- Contact Section -->
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="special-font">Neighborhood Info</h2>
                    <hr class="star-primary">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                   <p><%= @neighborhood.description %></p>

                </div>
            </div>
        </div>
    </section>



        </div>
    </div>
<footer class="text-center">
            <div class="footer-above">
            <div class="container">
                <div class="row get-out-there">
                <h1 class="special-font" id="closing-words">Get out there, and enjoy beautiful San Francisco!</h1>

                </div>
            </div>
        </div></footer>


    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/freelancer.min.js"></script>

</body>

</html>